plugins:
  - jekyll-paginate
  - jekyll-feed

title: shodanwashere
description: "shodan, aka, Nuno Dias' personal blog"
url: "https://shodanwashere.github.io"
author: "Nuno Dias"
paginate: 10
paginate_path: "/blog/page:num/"
